-- corrected headline (drops the HOSPITALS-only requirement)
SELECT
  CASE WHEN IS_AUTHORIZED_ATC = 1
        AND (HCO_COMMUNITY_NETWORK IS NULL
             OR HCO_COMMUNITY_NETWORK NOT IN
                ('THE US ONCOLOGY NETWORK','ONE ONCOLOGY','AMERICAN ONCOLOGY NETWORK'))
       THEN 'ATC' ELSE 'Non-ATC' END AS SITE_OF_CARE_V2,
  COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS,
  ROUND(100.0*COUNT(DISTINCT D_PATIENT_ID)/SUM(COUNT(DISTINCT D_PATIENT_ID)) OVER(),1) AS PCT
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025
GROUP BY 1;

-- the parent list KK actually asked for: ATC parents by patient volume
SELECT HCO_PARENT_NAME,
       COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS,
       COUNT(DISTINCT D_PRIMARY_HCO_COMPILE_ID) AS DISTINCT_HCOS,
       SUM(TREATMENT_CLAIMS) AS TOTAL_CLAIMS
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025
WHERE SITE_OF_CARE = 'ATC'
GROUP BY 1 ORDER BY 2 DESC;