-- 1. HCO_TYPE distribution
SELECT HCO_TYPE, COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025
GROUP BY 1 ORDER BY 2 DESC;

-- 2. Join coverage
SELECT
    COUNT(DISTINCT D_PATIENT_ID) AS TOTAL_PATIENTS,
    COUNT(DISTINCT CASE WHEN HCO_TYPE IS NULL THEN D_PATIENT_ID END) AS MISSING_HCO_ATTR,
    COUNT(DISTINCT CASE WHEN IS_AUTHORIZED_ATC IS NULL THEN D_PATIENT_ID END) AS MISSING_ATC_FLAG
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025;

-- 3. Unmapped states
SELECT PRIMARY_HCO_NPI_STATE, COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025
WHERE PRIMARY_HCO_NPI_STATE NOT IN (SELECT STATE FROM COMPILE_DEV.PUBLIC.STATE_REGION_MAP)
GROUP BY 1 ORDER BY 2 DESC;

-- 4. NPI state vs attribute state mismatch
SELECT COUNT(*) AS TOTAL,
    SUM(CASE WHEN PRIMARY_HCO_NPI_STATE <> HCO_STATE THEN 1 ELSE 0 END) AS STATE_MISMATCH
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025
WHERE HCO_STATE IS NOT NULL;


-- 5. Funnel (diagnosed vs treated), straight off the source table
SELECT
  COUNT(DISTINCT CASE WHEN D_DIAGNOSIS_CODE_ALL ILIKE '%C43%'
                       AND D_DIAGNOSIS_CODE_ALL ILIKE ANY ('%C77%','%C78%','%C79%')
                      THEN D_PATIENT_ID END) AS DIAGNOSED,
  COUNT(DISTINCT CASE WHEN D_NDC_CODE IN ('00003232711','00003232822','00003712511')
                       OR D_PROCEDURE_CODE IN ('J9228','J9298')
                      THEN D_PATIENT_ID END) AS TREATED
FROM COMPILE_CLAIMS.OPEN_CLAIMS.IOV2501_MEDICAL_CLAIMS
WHERE D_PATIENT_ID <> 'XXX - HIDDEN'
  AND DATE_OF_SERVICE >= DATE '2021-01-01'
  AND DATE_OF_SERVICE < DATE '2026-01-01';




  -- crosstab: are authorized patients getting dropped from ATC, and is the hospital bucket full of NULLs?
SELECT COALESCE(TO_VARCHAR(IS_AUTHORIZED_ATC),'null') AS ATC_FLAG,
       COALESCE(HCO_TYPE,'null') AS HCO_TYPE,
       COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025
GROUP BY 1,2 ORDER BY 1,3 DESC;

-- the headline split itself
SELECT SITE_OF_CARE, COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS,
       ROUND(100.0*COUNT(DISTINCT D_PATIENT_ID)/SUM(COUNT(DISTINCT D_PATIENT_ID)) OVER(),1) AS PCT
FROM COMPILE_DEV.PUBLIC.ATC_SOC_PATIENT_CLASSIFIED_2021_2025
GROUP BY 1 ORDER BY 2 DESC;