-- ATC vs Non-ATC follow-ups
-- Requires base tables from "Diagnosed & Treated Patients - ATC vs Non-ATC Split.sql"


-- A: Roster status check
SELECT
    UPPER(TRIM("Status")) AS STATUS,
    COUNT(*) AS ROSTER_ROWS,
    COUNT(DISTINCT TRIM("NPI")) AS DISTINCT_NPIS,
    COUNT(DISTINCT UPPER(TRIM("ATC HCO Parent Name (McKesson Claims)"))) AS DISTINCT_PARENTS
FROM COMPILE_DEV.PUBLIC.CTAM_ATC_ALIGNMENT_2026
GROUP BY 1
ORDER BY 2 DESC;

-- A2: Patients at non-authorized roster NPIs
WITH non_auth_npi AS (
    SELECT DISTINCT TRIM("NPI") AS NPI
    FROM COMPILE_DEV.PUBLIC.CTAM_ATC_ALIGNMENT_2026
    WHERE UPPER(TRIM("Status")) <> 'AUTHORIZED'
      AND "NPI" IS NOT NULL
      AND TRIM("NPI") NOT IN ('0', '', 'NPI')
)
SELECT
    a.CLASS_FINAL,
    COUNT(DISTINCT a.D_PATIENT_ID) AS PATIENTS_AT_NON_AUTH_NPIS
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
INNER JOIN non_auth_npi n ON TRIM(a.D_PRIMARY_HCO_NPI) = n.NPI
GROUP BY 1
ORDER BY 2 DESC;


-- B1: True ATC site vs satellite, within ATC patients
SELECT
    CASE
        WHEN CLASS_HYBRID = 'ATC: NPI confirmed' THEN 'True ATC site (NPI on authorized list)'
        ELSE 'Satellite (ATC parent, site not on list)'
    END AS SITE_TYPE,
    COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS,
    ROUND(100.0 * COUNT(DISTINCT D_PATIENT_ID)
        / SUM(COUNT(DISTINCT D_PATIENT_ID)) OVER (), 1) AS PCT_OF_ATC
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
WHERE CLASS_FINAL = 'ATC'
GROUP BY 1
ORDER BY 2 DESC;


-- B2: Satellite share by ATC parent (min 10 patients)
SELECT
    HCO_PARENT_NAME,
    COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS,
    COUNT(DISTINCT CASE WHEN CLASS_HYBRID = 'ATC: NPI confirmed'
        THEN D_PATIENT_ID END) AS TRUE_SITE_PATIENTS,
    COUNT(DISTINCT CASE WHEN CLASS_HYBRID <> 'ATC: NPI confirmed'
        THEN D_PATIENT_ID END) AS SATELLITE_PATIENTS,
    ROUND(100.0 * COUNT(DISTINCT CASE WHEN CLASS_HYBRID <> 'ATC: NPI confirmed'
        THEN D_PATIENT_ID END)
        / NULLIF(COUNT(DISTINCT D_PATIENT_ID), 0), 1) AS PCT_SATELLITE
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
WHERE CLASS_FINAL = 'ATC'
GROUP BY 1
HAVING COUNT(DISTINCT D_PATIENT_ID) >= 10
ORDER BY SATELLITE_PATIENTS DESC
LIMIT 25;


-- B3: Headline split with NPI-confirmed sites only
SELECT
    CASE
        WHEN CLASS_HYBRID = 'ATC: NPI confirmed' THEN 'ATC (true sites only)'
        ELSE 'Non-ATC (incl. satellites)'
    END AS SITE_GROUP,
    COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS,
    ROUND(100.0 * COUNT(DISTINCT D_PATIENT_ID)
        / SUM(COUNT(DISTINCT D_PATIENT_ID)) OVER (), 1) AS PCT
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
GROUP BY 1
ORDER BY 2 DESC;


-- C: ATC share by treatment year
SELECT
    TX_YEAR,
    COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS_TREATED,
    COUNT(DISTINCT CASE WHEN IS_ATC_HCO = 1 THEN D_PATIENT_ID END) AS ATC_PATIENTS,
    ROUND(100.0 * COUNT(DISTINCT CASE WHEN IS_ATC_HCO = 1 THEN D_PATIENT_ID END)
        / NULLIF(COUNT(DISTINCT D_PATIENT_ID), 0), 1) AS PCT_ATC
FROM COMPILE_DEV.PUBLIC.ATC_PATIENT_HCO_YEAR
GROUP BY 1
ORDER BY 1;


-- D1: Central region, ATC share by state
SELECT
    a.PRIMARY_HCO_NPI_STATE AS STATE,
    COUNT(DISTINCT a.D_PATIENT_ID) AS TOTAL_PATIENTS,
    COUNT(DISTINCT CASE WHEN a.CLASS_FINAL = 'ATC' THEN a.D_PATIENT_ID END) AS ATC_PATIENTS,
    ROUND(100.0 * COUNT(DISTINCT CASE WHEN a.CLASS_FINAL = 'ATC' THEN a.D_PATIENT_ID END)
        / NULLIF(COUNT(DISTINCT a.D_PATIENT_ID), 0), 1) AS PCT_ATC
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
INNER JOIN COMPILE_DEV.PUBLIC.STATE_REGION_MAP r
    ON a.PRIMARY_HCO_NPI_STATE = r.STATE
WHERE r.REGION = 'Central'
GROUP BY 1
ORDER BY 2 DESC;


-- D2: ATC site and parent counts by region
SELECT
    COALESCE(r.REGION, 'Unmapped') AS REGION,
    COUNT(DISTINCT CASE WHEN a.CLASS_FINAL = 'ATC'
        THEN a.D_PRIMARY_HCO_COMPILE_ID END) AS ATC_SITES,
    COUNT(DISTINCT CASE WHEN a.CLASS_FINAL = 'ATC'
        THEN a.HCO_PARENT_NAME END) AS ATC_PARENTS,
    COUNT(DISTINCT a.D_PATIENT_ID) AS TOTAL_PATIENTS,
    ROUND(1.0 * COUNT(DISTINCT a.D_PATIENT_ID)
        / NULLIF(COUNT(DISTINCT CASE WHEN a.CLASS_FINAL = 'ATC'
            THEN a.D_PRIMARY_HCO_COMPILE_ID END), 0), 1) AS PATIENTS_PER_ATC_SITE
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
LEFT JOIN COMPILE_DEV.PUBLIC.STATE_REGION_MAP r
    ON a.PRIMARY_HCO_NPI_STATE = r.STATE
GROUP BY 1
ORDER BY TOTAL_PATIENTS DESC;


-- D3: Top non-ATC parents in Central
SELECT
    a.HCO_PARENT_NAME,
    COUNT(DISTINCT a.D_PATIENT_ID) AS PATIENTS,
    COUNT(DISTINCT a.D_PRIMARY_HCO_COMPILE_ID) AS DISTINCT_HCOS,
    ROUND(100.0 * COUNT(DISTINCT a.D_PATIENT_ID)
        / SUM(COUNT(DISTINCT a.D_PATIENT_ID)) OVER (), 1) AS PCT_OF_CENTRAL_NON_ATC
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
INNER JOIN COMPILE_DEV.PUBLIC.STATE_REGION_MAP r
    ON a.PRIMARY_HCO_NPI_STATE = r.STATE
WHERE r.REGION = 'Central'
  AND a.CLASS_FINAL LIKE 'Non-ATC%'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 20;


-- E: Sample migration-cohort patient journeys (random 3)
WITH first_site AS (
    SELECT D_PATIENT_ID, IS_ATC_HCO AS FIRST_ATC
    FROM COMPILE_DEV.PUBLIC.ATC_TREATMENT_CLAIMS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY D_PATIENT_ID
        ORDER BY DATE_OF_SERVICE, D_PRIMARY_HCO_COMPILE_ID) = 1
),
sample_migrants AS (
    SELECT c.D_PATIENT_ID
    FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL c
    INNER JOIN first_site fs ON c.D_PATIENT_ID = fs.D_PATIENT_ID
    WHERE c.CLASS_FINAL = 'ATC'
      AND fs.FIRST_ATC = 0
    ORDER BY RANDOM()
    LIMIT 3
)
SELECT
    t.D_PATIENT_ID,
    t.DATE_OF_SERVICE,
    t.DRUG,
    CASE WHEN t.IS_ATC_HCO = 1 THEN 'ATC' ELSE 'Non-ATC' END AS SITE_TYPE,
    t.D_PRIMARY_HCO_COMPILE_ID,
    t.FIRST_DX_DATE,
    DATEDIFF("day", t.FIRST_DX_DATE, t.DATE_OF_SERVICE) AS DAYS_SINCE_DX
FROM COMPILE_DEV.PUBLIC.ATC_TREATMENT_CLAIMS t
INNER JOIN sample_migrants s ON t.D_PATIENT_ID = s.D_PATIENT_ID
ORDER BY t.D_PATIENT_ID, t.DATE_OF_SERVICE;


-- E2: Same journeys, fixed to the 3 patients sampled on Jul 7
SELECT
    t.D_PATIENT_ID,
    t.DATE_OF_SERVICE,
    t.DRUG,
    CASE WHEN t.IS_ATC_HCO = 1 THEN 'ATC' ELSE 'Non-ATC' END AS SITE_TYPE,
    t.D_PRIMARY_HCO_COMPILE_ID,
    t.FIRST_DX_DATE,
    DATEDIFF("day", t.FIRST_DX_DATE, t.DATE_OF_SERVICE) AS DAYS_SINCE_DX
FROM COMPILE_DEV.PUBLIC.ATC_TREATMENT_CLAIMS t
WHERE t.D_PATIENT_ID IN (
    '6f9979fa-d3ea-546e-a626-f8f1f5197c06',
    'af1edc05-ab01-5c5d-ad24-42a1cc5287a1',
    'f736b929-8ffb-5b4b-80ce-0faf319ce1b5'
)
ORDER BY t.D_PATIENT_ID, t.DATE_OF_SERVICE;


-- F: Start-site x End-classification 2x2 -- fills the four-bucket graphic on deck Slide 4
-- START = site of the patient's FIRST treatment claim (IS_ATC_HCO, NPI-strict) -- the same
--         definition already behind the 3,701 "moved to ATC" number (query E's first_site).
-- END   = CLASS_FINAL (hybrid, parent-level) -- the deck's headline 42.7% definition.
-- Built-in check: the 'Started Non-ATC' x 'Ended ATC' cell should return 3,701, and all
-- cells (incl. any 'No treatment claim') must sum to 16,246. If not, something changed upstream.
WITH first_site AS (
    SELECT D_PATIENT_ID, IS_ATC_HCO AS FIRST_ATC
    FROM COMPILE_DEV.PUBLIC.ATC_TREATMENT_CLAIMS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY D_PATIENT_ID
        ORDER BY DATE_OF_SERVICE, D_PRIMARY_HCO_COMPILE_ID) = 1
)
SELECT
    CASE
        WHEN fs.FIRST_ATC = 1 THEN 'Started ATC'
        WHEN fs.FIRST_ATC = 0 THEN 'Started Non-ATC'
        ELSE 'No treatment claim'
    END AS START_SITE,
    CASE WHEN c.CLASS_FINAL = 'ATC' THEN 'Ended ATC' ELSE 'Ended Non-ATC' END AS END_CLASS,
    COUNT(DISTINCT c.D_PATIENT_ID) AS PATIENTS,
    ROUND(100.0 * COUNT(DISTINCT c.D_PATIENT_ID)
        / SUM(COUNT(DISTINCT c.D_PATIENT_ID)) OVER (), 1) AS PCT_OF_ALL
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL c
LEFT JOIN first_site fs ON c.D_PATIENT_ID = fs.D_PATIENT_ID
GROUP BY 1, 2
ORDER BY 1, 2;
