/* Data for slides 6, 7, 8, 9 - correction applied ON READ (no rebuild needed).
   The four roster-gap orgs are forced to ATC inside each query, so results match
   the corrected 46.2% headline without touching the table.
   Run all four. Slide 6 ATC total should now sum to 7,501 (not 6,935). */


-- ============ SLIDE 6 - Regional opportunity ============
WITH b AS (
    SELECT a.*, r.REGION,
        CASE WHEN UPPER(TRIM(a.HCO_PARENT_NAME)) IN (
                'CITY OF HOPE','NYU LANGONE HEALTH SYSTEM',
                'THE OHIO STATE UNIVERSITY WEXNER MEDICAL CENTER','HOAG HOSPITAL NEWPORT BEACH')
             THEN 'ATC' ELSE a.CLASS_FINAL END AS CLASS_CORR
    FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
    LEFT JOIN COMPILE_DEV.PUBLIC.STATE_REGION_MAP r ON a.PRIMARY_HCO_NPI_STATE = r.STATE
)
SELECT
    COALESCE(REGION,'Unmapped') AS REGION_NAME,
    COUNT(DISTINCT CASE WHEN CLASS_CORR='ATC'         THEN D_PATIENT_ID END) AS AT_ATC,
    COUNT(DISTINCT CASE WHEN CLASS_CORR LIKE 'Non-ATC%' THEN D_PATIENT_ID END) AS UNTAPPED,
    ROUND(100.0*COUNT(DISTINCT CASE WHEN CLASS_CORR='ATC' THEN D_PATIENT_ID END)
        /NULLIF(COUNT(DISTINCT CASE WHEN CLASS_CORR='ATC' OR CLASS_CORR LIKE 'Non-ATC%' THEN D_PATIENT_ID END),0),1) AS PENETRATION_PCT
FROM b GROUP BY 1 ORDER BY UNTAPPED DESC;


-- ============ SLIDE 7 - State-level scatter ============
WITH b AS (
    SELECT a.*, r.REGION,
        CASE WHEN UPPER(TRIM(a.HCO_PARENT_NAME)) IN (
                'CITY OF HOPE','NYU LANGONE HEALTH SYSTEM',
                'THE OHIO STATE UNIVERSITY WEXNER MEDICAL CENTER','HOAG HOSPITAL NEWPORT BEACH')
             THEN 'ATC' ELSE a.CLASS_FINAL END AS CLASS_CORR
    FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
    LEFT JOIN COMPILE_DEV.PUBLIC.STATE_REGION_MAP r ON a.PRIMARY_HCO_NPI_STATE = r.STATE
)
SELECT
    PRIMARY_HCO_NPI_STATE AS STATE,
    COALESCE(REGION,'Unmapped') AS REGION_NAME,
    COUNT(DISTINCT CASE WHEN CLASS_CORR='ATC'         THEN D_PATIENT_ID END) AS AT_ATC,
    COUNT(DISTINCT CASE WHEN CLASS_CORR LIKE 'Non-ATC%' THEN D_PATIENT_ID END) AS UNTAPPED,
    ROUND(100.0*COUNT(DISTINCT CASE WHEN CLASS_CORR='ATC' THEN D_PATIENT_ID END)
        /NULLIF(COUNT(DISTINCT CASE WHEN CLASS_CORR='ATC' OR CLASS_CORR LIKE 'Non-ATC%' THEN D_PATIENT_ID END),0),1) AS PENETRATION_PCT
FROM b GROUP BY 1,2
HAVING COUNT(DISTINCT CASE WHEN CLASS_CORR LIKE 'Non-ATC%' THEN D_PATIENT_ID END) >= 20
ORDER BY UNTAPPED DESC;


-- ============ SLIDE 8 - Top 3 non-ATC accounts per region ============
-- The four gap orgs are now ATC, so they no longer appear here.
WITH b AS (
    SELECT a.HCO_PARENT_NAME, a.D_PATIENT_ID, r.REGION,
        CASE WHEN UPPER(TRIM(a.HCO_PARENT_NAME)) IN (
                'CITY OF HOPE','NYU LANGONE HEALTH SYSTEM',
                'THE OHIO STATE UNIVERSITY WEXNER MEDICAL CENTER','HOAG HOSPITAL NEWPORT BEACH')
             THEN 'ATC' ELSE a.CLASS_FINAL END AS CLASS_CORR
    FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
    LEFT JOIN COMPILE_DEV.PUBLIC.STATE_REGION_MAP r ON a.PRIMARY_HCO_NPI_STATE = r.STATE
),
nonatc AS (
    SELECT COALESCE(REGION,'Unmapped') AS REGION_NAME,
           COALESCE(NULLIF(TRIM(HCO_PARENT_NAME),''),'Unknown / unmapped') AS PARENT,
           COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS
    FROM b WHERE CLASS_CORR LIKE 'Non-ATC%' GROUP BY 1,2
),
ranked AS (
    SELECT REGION_NAME, PARENT, PATIENTS,
           ROW_NUMBER() OVER (PARTITION BY REGION_NAME ORDER BY PATIENTS DESC) AS RN
    FROM nonatc
)
SELECT REGION_NAME, PARENT, PATIENTS FROM ranked WHERE RN <= 3
ORDER BY REGION_NAME, PATIENTS DESC;


-- ============ SLIDE 9 - Concentration by segment ============
WITH b AS (
    SELECT a.HCO_PARENT_NAME, a.D_PATIENT_ID,
        CASE WHEN UPPER(TRIM(a.HCO_PARENT_NAME)) IN (
                'CITY OF HOPE','NYU LANGONE HEALTH SYSTEM',
                'THE OHIO STATE UNIVERSITY WEXNER MEDICAL CENTER','HOAG HOSPITAL NEWPORT BEACH')
             THEN 'ATC' ELSE a.CLASS_FINAL END AS CLASS_CORR
    FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
),
parents AS (
    SELECT COALESCE(NULLIF(TRIM(HCO_PARENT_NAME),''),'Unknown / unmapped') AS PARENT,
           COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS
    FROM b WHERE CLASS_CORR LIKE 'Non-ATC%' GROUP BY 1
),
ranked AS (
    SELECT PARENT, PATIENTS,
           ROW_NUMBER() OVER (ORDER BY PATIENTS DESC) AS RN,
           SUM(PATIENTS) OVER () AS TOT,
           SUM(PATIENTS) OVER (ORDER BY PATIENTS DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RUNNING
    FROM parents
)
SELECT
    (SELECT COUNT(*) FROM parents)                            AS TOTAL_ACCOUNTS,
    MAX(TOT)                                                  AS TOTAL_NONATC_PATIENTS,
    ROUND(100.0*SUM(CASE WHEN RN<=10 THEN PATIENTS END)/MAX(TOT),1) AS TOP10_SHARE_PCT,
    MIN(CASE WHEN RUNNING >= 0.50*TOT THEN RN END)            AS ACCOUNTS_TO_50PCT,
    MIN(CASE WHEN RUNNING >= 0.80*TOT THEN RN END)            AS ACCOUNTS_TO_80PCT
FROM ranked;