-- Q_SUMMARY : site-of-care split (must tie to the deck: ATC 7,501 / Hospital 7,100 / Community 1,317 / Other 328 / total 16,246)
WITH bucketed AS (
  SELECT D_PATIENT_ID,
    CASE WHEN CLASS_FINAL = 'ATC' THEN 'ATC Network'
         WHEN CLASS_FINAL = 'Non-ATC: Community Network' THEN 'Non-ATC: Community network'
         WHEN CLASS_FINAL IN ('Non-ATC: Unknown','Needs Review') THEN 'Non-ATC: Other'
         ELSE 'Non-ATC: Hospital' END AS SITE_OF_CARE
  FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
)
SELECT SITE_OF_CARE, COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS
FROM bucketed GROUP BY 1 ORDER BY PATIENTS DESC;

-- Q_ATC : one row per ATC parent account (this is the core deliverable). Sum of PATIENTS ~ 7,501.
SELECT HCO_PARENT_NAME AS ATC_ACCOUNT,
       COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS,
       COUNT(DISTINCT PRIMARY_HCO_NPI_STATE) AS STATES,
       CASE WHEN COUNT_IF(CLASS_HYBRID = 'ATC: NPI confirmed') > 0 THEN 'NPI-confirmed'
            WHEN COUNT_IF(CLASS_HYBRID = 'ATC: roster gap corrected') > 0 THEN 'Roster-confirmed'
            ELSE 'Name-matched' END AS MATCH_BASIS
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
WHERE CLASS_FINAL = 'ATC'
GROUP BY 1 ORDER BY PATIENTS DESC;

-- Q_UNTAPPED : largest non-ATC accounts by region. Sum of PATIENTS ~ 8,745.
SELECT COALESCE(NULLIF(TRIM(a.HCO_PARENT_NAME),''),'Unknown / unmapped') AS ACCOUNT,
       r.REGION,
       COUNT(DISTINCT a.D_PATIENT_ID) AS PATIENTS
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL a
LEFT JOIN COMPILE_DEV.PUBLIC.STATE_REGION_MAP r ON a.PRIMARY_HCO_NPI_STATE = r.STATE
WHERE a.CLASS_FINAL <> 'ATC'
GROUP BY 1, 2 ORDER BY PATIENTS DESC;