/* THREE UNMINED INSIGHTS from ATC_CLASSIFIED_FINAL. Run in SNOWFLAKE, paste back all rows.
   These complete the extraction of the classified table (staged 07/23). */

-- Q1: ACTIVE CENSUS. Historical totals vs patients still in treatment recently.
--     The non-ATC recent rows are the real, still-referrable opportunity.
SELECT
    CLASS_FINAL,
    COUNT(DISTINCT D_PATIENT_ID) AS PATIENTS_ALL_TIME,
    COUNT(DISTINCT CASE WHEN LAST_TREATMENT_DATE >= DATEADD(day, -90,  CURRENT_DATE) THEN D_PATIENT_ID END) AS ACTIVE_90D,
    COUNT(DISTINCT CASE WHEN LAST_TREATMENT_DATE >= DATEADD(day, -180, CURRENT_DATE) THEN D_PATIENT_ID END) AS ACTIVE_180D
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
GROUP BY 1
ORDER BY PATIENTS_ALL_TIME DESC;

-- Q2: EXPANSION CANDIDATES. Non-ATC parents ranked by how ATC-like they are:
--     volume, academic flag, hospital type, footprint, and recent activity.
SELECT
    HCO_PARENT_NAME                                   AS PARENT,
    MAX(HCO_TYPE)                                     AS HCO_TYPE,
    MAX(CASE WHEN HCO_ACADEMIC_FLAG THEN 1 ELSE 0 END) AS ACADEMIC,
    MAX(PARENT_STATES)                                AS STATES,
    COUNT(DISTINCT D_PATIENT_ID)                      AS PATIENTS,
    COUNT(DISTINCT CASE WHEN LAST_TREATMENT_DATE >= DATEADD(day, -180, CURRENT_DATE) THEN D_PATIENT_ID END) AS ACTIVE_180D,
    SUM(TREATMENT_CLAIMS)                             AS TOTAL_CLAIMS
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
WHERE CLASS_FINAL LIKE 'Non-ATC%'
GROUP BY 1
HAVING COUNT(DISTINCT D_PATIENT_ID) >= 25
ORDER BY ACTIVE_180D DESC, PATIENTS DESC
LIMIT 40;

-- Q3: PERSISTENCE. Do ATC patients stay on therapy longer? Claims per patient by class.
SELECT
    CLASS_FINAL,
    COUNT(DISTINCT D_PATIENT_ID)                    AS PATIENTS,
    ROUND(AVG(TREATMENT_CLAIMS), 1)                 AS AVG_CLAIMS_PER_PATIENT,
    ROUND(MEDIAN(TREATMENT_CLAIMS), 1)              AS MEDIAN_CLAIMS_PER_PATIENT
FROM COMPILE_DEV.PUBLIC.ATC_CLASSIFIED_FINAL
GROUP BY 1
ORDER BY PATIENTS DESC;
